local h = require("spec.support.harness")
local lexer = require("omelette.lexer")
local parser = require("omelette.parser")
local codegen = require("omelette.codegen")
local function prog(s) return assert(parser.parse(s)) end

h.describe("annotations", function()
  h.it("lexes : as an op", function()
    local toks = assert(lexer.tokenize("x : number"))
    h.eq(toks[2], { type = "op", value = ":", line = 1, col = 3 })
  end)
  h.it("parses a typed value binding", function()
    local e = prog("let count: number = 0").stmts[1]
    h.eq(e.value_type, { kind = "type_name", name = "number" })
    h.eq(e.params, nil)
  end)
  h.it("parses typed params and a return type", function()
    local e = prog("let add (x: number) (y: number): number = x + y").stmts[1]
    h.eq(e.params, { "x", "y" })
    h.eq(e.param_types[1], { kind = "type_name", name = "number" })
    h.eq(e.param_types[2], { kind = "type_name", name = "number" })
    h.eq(e.ret_type, { kind = "type_name", name = "number" })
  end)
  h.it("mixes typed and untyped params (untyped => false)", function()
    local e = prog("let f (x: number) y = x").stmts[1]
    h.eq(e.params, { "x", "y" })
    h.eq(e.param_types[1], { kind = "type_name", name = "number" })
    h.eq(e.param_types[2], false)
  end)
  h.it("parses a function type annotation", function()
    local e = prog("let g: (number, string) -> boolean = h").stmts[1]
    h.eq(e.value_type.kind, "fun_type")
    h.eq(#e.value_type.params, 2)
    h.eq(e.value_type.params[1].name, "number")
    h.eq(e.value_type.ret, { kind = "type_name", name = "boolean" })
  end)
  h.it("still parses untyped defs (regression)", function()
    local e = prog("let f x y = x + y").stmts[1]
    h.eq(e.params, { "x", "y" })
    h.eq(e.param_types, nil)
  end)
  h.it("ERASURE: annotated program emits identical Lua to unannotated", function()
    local typed = codegen.program(prog("pub let add (x: number) (y: number): number = x + y"))
    local plain = codegen.program(prog("pub let add x y = x + y"))
    h.eq(typed, plain)
  end)
end)
