local h = require("spec.support.harness")
local parser = require("omelette.parser")
local codegen = require("omelette.codegen")
local function gen(s) return codegen.program(assert(parser.parse(s))) end

h.describe("codegen/module", function()
  h.it("wraps output in a module table", function()
    local out = gen("let x = 1")
    h.truthy(out:find("local M = {}"))
    h.truthy(out:find("return M"))
    h.truthy(out:find("local x"))
    h.truthy(out:find("x = 1"))
  end)
  h.it("forward-declares and emits pub functions as locals aliased onto M", function()
    local out = gen("pub let add x y = x + y")
    h.truthy(out:find("local add"))                 -- forward declaration
    h.truthy(out:find("function add%(x, y%)"))       -- assignment form (no `local function`)
    h.truthy(out:find("M%.add = add"))               -- alias
    h.truthy(not out:find("local function add"))     -- old form gone
  end)
  h.it("forward-declares pub value bindings and aliases onto M", function()
    local out = gen("pub let x = 1")
    h.truthy(out:find("local x"))
    h.truthy(out:find("x = 1"))
    h.truthy(out:find("M%.x = x"))
  end)
  h.it("forward-declares non-pub functions (no M alias)", function()
    local out = gen("let inc x = x + 1")
    h.truthy(out:find("local inc"))
    h.truthy(out:find("function inc%(x%)"))
    h.truthy(not out:find("M%.inc"))
  end)
  h.it("lowers if in value position to statements", function()
    local out = gen("let r = if c then 1 else 2")
    h.truthy(out:find("local r"))
    h.truthy(out:find("if c then"))
    h.truthy(out:find("r = 1"))
    h.truthy(out:find("r = 2"))
    h.truthy(not out:find("and.-or"))  -- never the (c and a or b) idiom
  end)
  h.it("lowers match to an if/elseif chain", function()
    local out = gen('let r = match n with | 0 -> "z" | _ -> "m"')
    h.truthy(out:find("if n == 0 then"))
    h.truthy(out:find('r = "z"'))
    h.truthy(out:find('r = "m"'))
  end)
  h.it("lowers a block body", function()
    local out = gen("let f x = let y = x + 1 let z = y * 2 z")
    h.truthy(out:find("local f"))
    h.truthy(out:find("function f%(x%)"))
    h.truthy(out:find("local y = %(x %+ 1%)"))
    h.truthy(out:find("local z = %(y %* 2%)"))
    h.truthy(out:find("return z"))
  end)
end)
