local h = require("spec.support.harness")
local parser = require("omelette.parser")
local codegen = require("omelette.codegen")
local function gen(s)
  local e = assert(parser.parse_expr_string(s))
  return codegen.expr(e, codegen.new_ctx())
end

h.describe("codegen/expressions", function()
  h.it("emits literals", function()
    h.eq(gen("42"), "42")
    h.eq(gen('"hi"'), '"hi"')
    h.eq(gen("true"), "true")
    h.eq(gen("nil"), "nil")
  end)
  h.it("emits binops with parens for safety", function()
    h.eq(gen("1 + 2 * 3"), "(1 + (2 * 3))")
    h.eq(gen('"a" .. "b"'), '("a" .. "b")')
  end)
  h.it("maps ~= and not", function()
    h.eq(gen("a ~= b"), "(a ~= b)")
    h.eq(gen("not a"), "(not a)")
  end)
  h.it("emits calls verbatim including dotted fields", function()
    h.eq(gen("vim.api.foo(buf, 0)"), "vim.api.foo(buf, 0)")
  end)
  h.it("emits arrays and tables", function()
    h.eq(gen("[1, 2, 3]"), "{1, 2, 3}")
    h.eq(gen("{ x = 1, y = 2 }"), "{x = 1, y = 2}")
  end)
  h.it("threads pipe as first argument", function()
    h.eq(gen("a |> f(b)"), "f(a, b)")
    h.eq(gen("a |> g"), "g(a)")
  end)
  h.it("compiles holes to a wrapping closure", function()
    h.eq(gen("add(1, _)"), "(function(__p1) return add(1, __p1) end)")
  end)
  h.it("emits lambdas", function()
    h.eq(gen("fn x -> x + 1"), "function(x)\n  return (x + 1)\nend")
  end)
  h.it("emits raw lua verbatim", function()
    h.eq(gen('lua "os.time()"'), "os.time()")
  end)
  h.it("multi-hole ordering: both holes become __p1, __p2 in order", function()
    h.eq(gen("add(_, _)"), "(function(__p1, __p2) return add(__p1, __p2) end)")
  end)
  h.it("pipe-into-hole composes a partial-application closure", function()
    h.eq(gen("a |> add(b, _)"), "(function(__p1) return add(a, b, __p1) end)")
  end)
  h.it("error on non-expression node", function()
    h.truthy(h.throws(function() codegen.expr({ kind = "if" }, codegen.new_ctx()) end))
  end)
end)
