local h = require("spec.support.harness")
local compiler = require("omelette.compiler")

h.describe("compiler", function()
  h.it("compiles source to lua text", function()
    local lua, err = compiler.compile("pub let add x y = x + y")
    h.truthy(err == nil)
    h.truthy(lua:find("function add"))
    h.truthy(lua:find("M%.add = add"))
  end)
  h.it("surfaces lex/parse errors as diagnostics", function()
    local lua, err = compiler.compile('let x = "oops')
    h.truthy(lua == nil)
    h.truthy(err and err.message:find("string"))
  end)
  h.it("eval runs the module and exposes pub members (behavioral)", function()
    local mod, err = compiler.eval("pub let add x y = x + y")
    h.truthy(err == nil)
    h.eq(mod.add(2, 3), 5)
  end)
  h.it("behavioral: if-lowering returns the right branch", function()
    local mod = assert(compiler.eval("pub let pick c = if c then 10 else 20"))
    h.eq(mod.pick(true), 10)
    h.eq(mod.pick(false), 20)
  end)
  h.it("behavioral: match works including falsy branch values", function()
    local mod = assert(compiler.eval('pub let f n = match n with | 0 -> false | _ -> true'))
    h.eq(mod.f(0), false)   -- the (c and a or b) idiom would wrongly skip this
    h.eq(mod.f(7), true)
  end)
  h.it("behavioral: partial application via hole", function()
    local mod = assert(compiler.eval("let add x y = x + y\npub let inc = add(1, _)"))
    h.eq(mod.inc(9), 10)
  end)
  h.it("behavioral: pipe threads first arg", function()
    local mod = assert(compiler.eval(
      "let double x = x * 2\nlet add x y = x + y\npub let r = 5 |> double |> add(100)"))
    h.eq(mod.r, 110)
  end)
  h.it("behavioral: match cases fire in written order (non-final wildcard shadows later cases)", function()
    local mod = assert(compiler.eval('pub let f n = match n with | _ -> "other" | 0 -> "zero"'))
    h.eq(mod.f(0), "other")
    h.eq(mod.f(5), "other")
  end)
  h.it("behavioral: lambda with conditional body (if) evaluates correctly", function()
    local mod = assert(compiler.eval("pub let g = fn x -> if x then 1 else 2"))
    h.eq(mod.g(true), 1)
    h.eq(mod.g(false), 2)
  end)
  h.it("behavioral: a pub function can recurse by name", function()
    local mod = assert(compiler.eval(table.concat({
      "pub let fact n = if n <= 1 then 1 else n * fact(n - 1)",
    }, "\n")))
    h.eq(mod.fact(5), 120)
  end)
  h.it("behavioral: a pub function can call another pub function", function()
    local mod = assert(compiler.eval(table.concat({
      "pub let double x = x * 2",
      "pub let quad x = double(double(x))",
    }, "\n")))
    h.eq(mod.quad(3), 12)
  end)
end)
