local h = require("spec.support.harness")
local compiler = require("omelette.compiler")

h.describe("compiler", function()
  h.it("compiles source to lua text", function()
    local lua, err = compiler.compile("pub let add x y = x + y")
    h.truthy(err == nil)
    h.truthy(lua:find("function M%.add"))
  end)
  h.it("surfaces lex/parse errors as diagnostics", function()
    local lua, err = compiler.compile('let x = "oops')
    h.truthy(lua == nil)
    h.truthy(err and err.message:find("string"))
  end)
  h.it("eval runs the module and exposes pub members (behavioral)", function()
    local mod, err = compiler.eval("pub let add x y = x + y")
    h.truthy(err == nil)
    h.eq(mod.add(2, 3), 5)
  end)
  h.it("behavioral: if-lowering returns the right branch", function()
    local mod = assert(compiler.eval("pub let pick c = if c then 10 else 20"))
    h.eq(mod.pick(true), 10)
    h.eq(mod.pick(false), 20)
  end)
  h.it("behavioral: match works including falsy branch values", function()
    local mod = assert(compiler.eval('pub let f n = match n with | 0 -> false | _ -> true'))
    h.eq(mod.f(0), false)   -- the (c and a or b) idiom would wrongly skip this
    h.eq(mod.f(7), true)
  end)
  h.it("behavioral: partial application via hole", function()
    local mod = assert(compiler.eval("let add x y = x + y\npub let inc = add(1, _)"))
    h.eq(mod.inc(9), 10)
  end)
  h.it("behavioral: pipe threads first arg", function()
    local mod = assert(compiler.eval(
      "let double x = x * 2\nlet add x y = x + y\npub let r = 5 |> double |> add(100)"))
    h.eq(mod.r, 110)
  end)
end)
