local h = require("spec.support.harness")
local parser = require("omelette.parser")
local function expr(s) return assert(parser.parse_expr_string(s)) end

h.describe("parser/comprehension", function()
  h.it("still parses array literals (regression)", function()
    h.eq(expr("[1, 2, 3]").kind, "array")
    h.eq(#expr("[1, 2, 3]").items, 3)
    h.eq(expr("[]").kind, "array")
    h.eq(#expr("[]").items, 0)
    h.eq(expr("[7]").items[1].value, 7)
  end)
  h.it("parses a single-generator comprehension", function()
    local e = expr("[ x * 2 | x <- nums ]")
    h.eq(e.kind, "comprehension")
    h.eq(e.yield.kind, "binop")
    h.eq(#e.quals, 1)
    h.eq(e.quals[1], { kind = "generator", name = "x", source = e.quals[1].source })
    h.eq(e.quals[1].source.name, "nums")
  end)
  h.it("parses a guard after a generator", function()
    local e = expr("[ x | x <- xs, x > 0 ]")
    h.eq(#e.quals, 2)
    h.eq(e.quals[1].kind, "generator")
    h.eq(e.quals[2].kind, "guard")
    h.eq(e.quals[2].cond.kind, "binop")
  end)
  h.it("parses multiple generators and interleaved guards in order", function()
    local e = expr("[ [x, y] | x <- xs, x > 0, y <- ys ]")
    h.eq(e.yield.kind, "array")
    h.eq(#e.quals, 3)
    h.eq(e.quals[1].kind, "generator"); h.eq(e.quals[1].name, "x")
    h.eq(e.quals[2].kind, "guard")
    h.eq(e.quals[3].kind, "generator"); h.eq(e.quals[3].name, "y")
  end)
  h.it("treats a function-call qualifier as a guard, not a generator", function()
    local e = expr("[ x | x <- xs, even(x) ]")
    h.eq(e.quals[2].kind, "guard")
    h.eq(e.quals[2].cond.kind, "call")
  end)
  h.it("rejects a comprehension with no generator", function()
    local _, err = parser.parse_expr_string("[ x | x > 0 ]")
    h.truthy(err ~= nil)
    h.truthy(err.message:find("generator"))
  end)
end)
