local h = require("spec.support.harness")
local parser = require("omelette.parser")
local function prog(s) return assert(parser.parse(s)) end

h.describe("destructuring let — parsing", function()
  h.it("parses a record destructuring let", function()
    local node = prog("let { a } = r").stmts[1]
    h.eq(node.kind, "let")
    h.eq(node.pattern.kind, "record_pat")
    h.truthy(node.name == nil)
  end)
  h.it("parses an array destructuring let", function()
    h.eq(prog("let [a, b] = xs").stmts[1].pattern.kind, "array_pat")
  end)
  h.it("parses a tuple destructuring let (paren → array_pat)", function()
    h.eq(prog("let (a, b) = pair").stmts[1].pattern.kind, "array_pat")
  end)
  h.it("a normal value let is unaffected", function()
    local node = prog("let x = 1").stmts[1]
    h.eq(node.name, "x")
    h.truthy(node.pattern == nil)
  end)
  h.it("a normal function let is unaffected", function()
    local node = prog("let f a b = a").stmts[1]
    h.eq(node.name, "f")
    h.truthy(node.params ~= nil)
  end)
  h.it("rejects a refutable pattern (literal slot)", function()
    local ok = parser.parse("let [a, 0] = xs")
    h.truthy(not ok)
  end)
  h.it("rejects a refutable pattern (constructor slot)", function()
    local ok = parser.parse("let { x: Origin } = r")
    h.truthy(not ok)
  end)
end)
