local h = require("spec.support.harness")
local compiler = require("omelette.compiler")
local function eval(src) return assert(compiler.eval(src)) end

h.describe("destructuring let", function()
  h.it("record pun binds the field", function()
    h.eq(eval("pub let { a } = { a = 1, b = 2 }").a, 1)
  end)
  h.it("record rename binds the renamed var", function()
    h.eq(eval("pub let { a: x } = { a = 7 }").x, 7)
  end)
  h.it("nested record", function()
    local m = eval("pub let { p: { x, y } } = { p = { x = 3, y = 4 } }")
    h.eq(m.x, 3); h.eq(m.y, 4)
  end)
  h.it("array positional", function()
    local m = eval("pub let [a, b] = [10, 20, 30]")
    h.eq(m.a, 10); h.eq(m.b, 20)
  end)
  h.it("array shorter than pattern binds nil", function()
    h.eq(eval("pub let [a, b] = [1]").b, nil)
  end)
  h.it("tuple destructuring (paren) works", function()
    local m = eval("pub let (a, b) = (10, 20)")
    h.eq(m.a, 10); h.eq(m.b, 20)
  end)
  h.it("wildcard skips a slot", function()
    local m = eval("pub let [a, _, c] = [1, 2, 3]")
    h.eq(m.a, 1); h.eq(m.c, 3)
  end)
  h.it("pub exports every bound name", function()
    local m = eval("pub let { a, b } = { a = 1, b = 2 }")
    h.eq(m.a, 1); h.eq(m.b, 2)
  end)
  h.it("a destructured name is visible to later top-level bindings (forward-decl)", function()
    h.eq(eval("pub let { base } = { base = 2 }\npub let r = base * 3").r, 6)
  end)
  h.it("works at block scope inside a function", function()
    h.eq(eval("pub let f p =\n  let { x, y } = p\n  x + y\npub let r = f({ x = 3, y = 4 })").r, 7)
  end)
  h.it("evaluates a non-ident value exactly once", function()
    local lua = assert(compiler.compile("pub let { x } = distinctbase(1)"))
    local _, n = lua:gsub("distinctbase", "")
    h.eq(n, 1)
  end)
  h.it("the emitted Lua loads", function()
    local lua = assert(compiler.compile("pub let { a, b } = { a = 1, b = 2 }"))
    local load_fn = loadstring or load
    h.truthy((load_fn(lua)))
  end)
end)
