local h = require("spec.support.harness")
local dt = require("spec.support.doctest")

h.describe("doctest.extract", function()
  h.it("an egg block alone is smoke", function()
    local b = dt.extract("```egg\nprint(1)\n```")
    h.eq(#b, 1); h.eq(b[1].mode, "smoke"); h.eq(b[1].code, "print(1)")
  end)
  h.it("egg + output pairs into an output block", function()
    local b = dt.extract("```egg\nprint(1)\n```\n```output\n1\n```")
    h.eq(#b, 1); h.eq(b[1].mode, "output"); h.eq(b[1].expect, "1")
  end)
  h.it("egg + error pairs into an error block", function()
    local b = dt.extract("```egg\nx\n```\n```error\nboom\n```")
    h.eq(b[1].mode, "error"); h.eq(b[1].expect, "boom")
  end)
  h.it("egg followed by a non-expectation fence stays smoke", function()
    local b = dt.extract("```egg\nprint(1)\n```\n```lua\nwhatever\n```")
    h.eq(#b, 1); h.eq(b[1].mode, "smoke")
  end)
  h.it("ignores prose and non-egg fences", function()
    h.eq(#dt.extract("hello\n```text\nnope\n```\nworld"), 0)
  end)
  h.it("records the source line of the egg block", function()
    local b = dt.extract("intro\n\n```egg\nprint(1)\n```")
    h.eq(b[1].line, 3)
  end)
end)

h.describe("doctest.run_block", function()
  h.it("passes a correct smoke block", function()
    h.truthy((dt.run_block({ code = "let x = 1\nprint(x)", mode = "smoke" })))
  end)
  h.it("fails a smoke block that does not compile", function()
    h.truthy(not (dt.run_block({ code = "let = ", mode = "smoke" })))
  end)
  h.it("passes a correct output block", function()
    h.truthy((dt.run_block({ code = "print(2 + 3)", mode = "output", expect = "5" })))
  end)
  h.it("fails a wrong-output block", function()
    h.truthy(not (dt.run_block({ code = "print(2 + 3)", mode = "output", expect = "6" })))
  end)
  h.it("passes an error block whose diagnostic contains the text", function()
    h.truthy((dt.run_block({
      code = "type Shape = | Circle { radius } | Origin\n"
        .. "pub let f s = match s with | Circle { radius } -> radius",
      mode = "error", expect = "missing Origin" })))
  end)
  h.it("fails an error block that actually checks clean", function()
    h.truthy(not (dt.run_block({ code = "let x = 1", mode = "error", expect = "anything" })))
  end)
  h.it("fails an error block whose diagnostic lacks the text", function()
    h.truthy(not (dt.run_block({ code = 'let x: number = "hi"', mode = "error", expect = "zzz-not-present" })))
  end)
end)
