local h = require("spec.support.harness")
local errors = require("omelette.errors")

h.describe("errors", function()
  h.it("builds a diagnostic with position", function()
    local d = errors.new("bad token", 2, 5)
    h.eq(d.message, "bad token")
    h.eq(d.line, 2)
    h.eq(d.col, 5)
  end)
  h.it("extracts a snippet from source", function()
    local d = errors.new("oops", 2, 3, "line one\nline two\nline three")
    h.eq(d.snippet, "line two")
  end)
  h.it("renders with a caret", function()
    local d = errors.new("oops", 1, 3, "abcdef")
    h.truthy(d and errors.render(d):find("oops"))
    h.truthy(errors.render(d):find("%^"))
  end)
end)
