local h = require("spec.support.harness")

h.describe("harness", function()
  h.it("compares equal values", function()
    h.eq(1 + 1, 2)
    h.eq("a" .. "b", "ab")
  end)
  h.it("deep-compares tables", function()
    h.eq({ a = 1, b = { 2, 3 } }, { a = 1, b = { 2, 3 } })
  end)
  h.it("detects thrown errors", function()
    h.truthy(h.throws(function() error("boom") end))
    h.truthy(not h.throws(function() return 1 end))
  end)
end)
