local h = require("spec.support.harness")
local parser = require("omelette.parser")
local codegen = require("omelette.codegen")
local compiler = require("omelette.compiler")
local function gen(s) return codegen.expr(assert(parser.parse_expr_string(s)), codegen.new_ctx()) end
local function prog(s) return codegen.program(assert(parser.parse(s))) end

h.describe("if as expression", function()
  h.it("emits an IIFE returning from each branch", function()
    local out = gen("(if c then 1 else 2)")
    h.truthy(out:find("^%(function%(%)"))
    h.truthy(out:find("if c then"))
    h.truthy(out:find("return 1"))
    h.truthy(out:find("return 2"))
    h.truthy(out:find("end%)%(%)$"))
  end)
  h.it("regression: a let-bound if stays non-closure (statement lowering)", function()
    local out = prog("pub let f c = if c then 1 else 2")
    h.truthy(not out:find("%(function%(%)"))   -- no IIFE for the common case
    h.truthy(out:find("if c then"))
  end)

  h.it("behavioral: if as a binop operand", function()
    local mod = assert(compiler.eval("pub let f n = 1 + (if n > 0 then 10 else 20)"))
    h.eq(mod.f(5), 11); h.eq(mod.f(-1), 21)
  end)
  h.it("behavioral: if as a pipe LHS", function()
    local mod = assert(compiler.eval("pub let f c = (if c then 1 else 2) |> tostring"))
    h.eq(mod.f(true), "1"); h.eq(mod.f(false), "2")
  end)
  h.it("behavioral: if as a comprehension yield", function()
    local mod = assert(compiler.eval('pub let f xs = [ (if x > 0 then "p" else "n") | x <- xs ]'))
    h.eq(mod.f({ 1, -1, 2 }), { "p", "n", "p" })
  end)
  h.it("behavioral: if as a call argument (parenthesized)", function()
    local mod = assert(compiler.eval("pub let f c = tostring(if c then 1 else 2)"))
    h.eq(mod.f(true), "1")
  end)
  h.it("behavioral: falsy-safe", function()
    local mod = assert(compiler.eval("pub let f c = (if c then false else true)"))
    h.eq(mod.f(true), false); h.eq(mod.f(false), true)
  end)
  h.it("behavioral: nested if-expressions", function()
    local mod = assert(compiler.eval("pub let f a b = (if a then (if b then 1 else 2) else 3)"))
    h.eq(mod.f(true, true), 1); h.eq(mod.f(true, false), 2); h.eq(mod.f(false, false), 3)
  end)
end)
