local h = require("spec.support.harness")
local lexer = require("omelette.lexer")
local parser = require("omelette.parser")
local codegen = require("omelette.codegen")
local compiler = require("omelette.compiler")
local function gen(s) return codegen.expr(assert(parser.parse_expr_string(s)), codegen.new_ctx()) end

h.describe("length operator", function()
  h.it("lexes # as an op token", function()
    local toks = assert(lexer.tokenize("#xs"))
    h.eq(toks[1], { type = "op", value = "#", line = 1, col = 1 })
    h.eq(toks[2].value, "xs")
  end)
  h.it("parses #xs as a unop", function()
    local e = assert(parser.parse_expr_string("#xs"))
    h.eq(e.kind, "unop")
    h.eq(e.op, "#")
    h.eq(e.operand.name, "xs")
  end)
  h.it("binds tighter than binary operators", function()
    local e = assert(parser.parse_expr_string("#xs + 1"))
    h.eq(e.kind, "binop"); h.eq(e.op, "+")
    h.eq(e.lhs.kind, "unop"); h.eq(e.lhs.op, "#")
  end)
  h.it("emits (#x)", function()
    h.eq(gen("#xs"), "(#xs)")
  end)
  h.it("behavioral: length of an array and a string", function()
    local mod = assert(compiler.eval('pub let a = #[10, 20, 30]\npub let b = #"hello"'))
    h.eq(mod.a, 3)
    h.eq(mod.b, 5)
  end)
end)
