local h = require("spec.support.harness")
local lexer = require("omelette.lexer")

local function types(src)
  local toks = assert(lexer.tokenize(src))
  local out = {}
  for _, t in ipairs(toks) do out[#out + 1] = t.type end
  return out
end

h.describe("lexer", function()
  h.it("tokenizes numbers, idents, and ops", function()
    local toks = assert(lexer.tokenize("x + 12"))
    h.eq(toks[1], { type = "ident", value = "x", line = 1, col = 1 })
    h.eq(toks[2], { type = "op", value = "+", line = 1, col = 3 })
    h.eq(toks[3], { type = "number", value = 12, line = 1, col = 5 })
    h.eq(toks[4].type, "eof")
  end)
  h.it("recognizes keywords distinctly from idents", function()
    local toks = assert(lexer.tokenize("let pub fn match"))
    h.eq(toks[1], { type = "keyword", value = "let", line = 1, col = 1 })
    h.eq(toks[4].value, "match")
    h.eq(toks[4].type, "keyword")
  end)
  h.it("lexes strings with escapes", function()
    local toks = assert(lexer.tokenize([["a\nb"]]))
    h.eq(toks[1], { type = "string", value = "a\nb", line = 1, col = 1 })
  end)
  h.it("lexes multi-char operators", function()
    h.eq(types("a |> b -> c .. d == e ~= f <= g"),
      { "ident","op","ident","op","ident","op","ident","op","ident","op","ident","op","ident","eof" })
  end)
  h.it("skips comments and tracks lines", function()
    local toks = assert(lexer.tokenize("a -- comment\nb"))
    h.eq(toks[1].line, 1)
    h.eq(toks[2].line, 2)
    h.eq(toks[2].value, "b")
  end)
  h.it("treats _ as its own punct token", function()
    local toks = assert(lexer.tokenize("f(_)"))
    h.eq(toks[3], { type = "punct", value = "_", line = 1, col = 3 })
  end)
  h.it("returns a diagnostic on an unterminated string", function()
    local toks, err = lexer.tokenize('"oops')
    h.truthy(toks == nil)
    h.truthy(err and err.message:find("string"))
  end)
end)
