local h = require("spec.support.harness")
require("omelette.searcher").install()
local L = require("std.list")
local function dbl(x) return x * 2 end
local function even(x) return x % 2 == 0 end

h.describe("std.list", function()
  h.it("basics", function()
    h.eq(L.length({1,2,3}), 3)
    h.truthy(L.is_empty({}))
    h.eq(L.first({9,8}), 9)
    h.eq(L.last({9,8}), 8)
    h.eq(L.get({5,6,7}, 2), 6)
    h.eq(L.first({}), nil)
  end)
  h.it("map/filter", function()
    h.eq(L.map({1,2,3}, dbl), {2,4,6})
    h.eq(L.filter({1,2,3,4}, even), {2,4})
  end)
  h.it("reduce/sum/product", function()
    h.eq(L.reduce({1,2,3}, function(a,b) return a+b end, 0), 6)
    h.eq(L.sum({1,2,3,4}), 10)
    h.eq(L.product({1,2,3,4}), 24)
    h.eq(L.sum({}), 0)
  end)
  h.it("all/any/count/contains/index_of/find", function()
    h.truthy(L.all({2,4}, even))
    h.truthy(not L.all({2,3}, even))
    h.truthy(L.any({1,2}, even))
    h.eq(L.count({1,2,3,4}, even), 2)
    h.truthy(L.contains({1,2,3}, 2))
    h.truthy(not L.contains({1,2,3}, 9))
    h.eq(L.index_of({7,8,9}, 8), 2)
    h.eq(L.index_of({7,8,9}, 5), nil)
    h.eq(L.find({1,3,4,5}, even), 4)
    h.eq(L.find({1,3,5}, even), nil)
  end)
  h.it("min/max", function()
    h.eq(L.min({3,1,2}), 1)
    h.eq(L.max({3,1,2}), 3)
    h.eq(L.min({}), nil)
  end)
  h.it("range/reverse/take/drop/concat", function()
    h.eq(L.range(1, 4), {1,2,3,4})
    h.eq(L.reverse({1,2,3}), {3,2,1})
    h.eq(L.take({1,2,3,4}, 2), {1,2})
    h.eq(L.take({1,2}, 5), {1,2})
    h.eq(L.drop({1,2,3,4}, 2), {3,4})
    h.eq(L.concat({1,2}, {3,4}), {1,2,3,4})
  end)
  h.it("sort/sort_by (immutable)", function()
    local input = {3,1,2}
    h.eq(L.sort(input), {1,2,3})
    h.eq(input, {3,1,2})            -- input not mutated
    h.eq(L.sort_by({3,1,2}, function(a,b) return a > b end), {3,2,1})
  end)
  h.it("each runs side effects and returns nil", function()
    local seen = {}
    local r = L.each({1,2,3}, function(x) seen[#seen+1] = x end)
    h.eq(seen, {1,2,3})
    h.eq(r, nil)
  end)
end)
