local h = require("spec.support.harness")
local parser = require("omelette.parser")
local function expr(s) return assert(parser.parse_expr_string(s)) end

h.describe("parser/expressions", function()
  h.it("parses literals and idents", function()
    h.eq(expr("42").kind, "number")
    h.eq(expr("42").value, 42)
    h.eq(expr("true"), { kind = "bool", value = true, line = 1, col = 1 })
    h.eq(expr("x").name, "x")
  end)
  h.it("respects arithmetic precedence", function()
    local e = expr("1 + 2 * 3")
    h.eq(e.kind, "binop"); h.eq(e.op, "+")
    h.eq(e.rhs.kind, "binop"); h.eq(e.rhs.op, "*")
  end)
  h.it("parses calls with multiple args", function()
    local e = expr("add(1, 2)")
    h.eq(e.kind, "call")
    h.eq(e.fn.name, "add")
    h.eq(#e.args, 2)
    h.eq(e.args[2].value, 2)
  end)
  h.it("parses holes in call args", function()
    local e = expr("add(1, _)")
    h.eq(e.args[2].kind, "hole")
  end)
  h.it("parses dotted field access and chained calls", function()
    local e = expr("vim.api.nvim_get(buf)")
    h.eq(e.kind, "call")
    h.eq(e.fn.kind, "field")
    h.eq(e.fn.name, "nvim_get")
    h.eq(e.fn.obj.kind, "field")
    h.eq(e.fn.obj.name, "api")
  end)
  h.it("parses arrays and tables", function()
    h.eq(expr("[1, 2, 3]").kind, "array")
    h.eq(#expr("[1, 2, 3]").items, 3)
    local t = expr("{ x = 1, y = 2 }")
    h.eq(t.kind, "table")
    h.eq(t.fields[1].key, "x")
    h.eq(t.fields[2].value.value, 2)
  end)
  h.it("parses pipe as left-associative", function()
    local e = expr("a |> f(b) |> g")
    h.eq(e.kind, "pipe")
    h.eq(e.rhs.name, "g")
    h.eq(e.lhs.kind, "pipe")
  end)
  h.it("parses unary minus and string concat", function()
    h.eq(expr("-x").kind, "unop")
    h.eq(expr('"a" .. "b"').op, "..")
  end)
  h.it("parses raw lua escape hatch", function()
    h.eq(expr('lua "os.time()"'), { kind = "lua_raw", code = "os.time()", line = 1, col = 1 })
  end)
end)
