local h = require("spec.support.harness")
local parser = require("omelette.parser")
local function prog(s) return assert(parser.parse(s)) end

h.describe("parser/statements", function()
  h.it("parses a value binding", function()
    local p = prog("let x = 1")
    h.eq(p.kind, "program")
    h.eq(p.stmts[1].kind, "let")
    h.eq(p.stmts[1].name, "x")
    h.eq(p.stmts[1].params, nil)
    h.eq(p.stmts[1].is_pub, false)
    h.eq(p.stmts[1].value.value, 1)
  end)
  h.it("parses a pub function definition with params", function()
    local p = prog("pub let add x y = x + y")
    local s = p.stmts[1]
    h.eq(s.is_pub, true)
    h.eq(s.name, "add")
    h.eq(s.params, { "x", "y" })
    h.eq(s.value.kind, "binop")
  end)
  h.it("parses a lambda", function()
    local p = prog("let inc = fn x -> x + 1")
    h.eq(p.stmts[1].value.kind, "lambda")
    h.eq(p.stmts[1].value.params, { "x" })
    h.eq(p.stmts[1].value.body.kind, "binop")
  end)
  h.it("parses if/then/else as an expression", function()
    local p = prog("let r = if x then 1 else 2")
    local e = p.stmts[1].value
    h.eq(e.kind, "if")
    h.eq(e.then_branch.value, 1)
    h.eq(e.else_branch.value, 2)
  end)
  h.it("parses match with literal and wildcard cases", function()
    local p = prog('let r = match n with | 0 -> "z" | _ -> "m"')
    local e = p.stmts[1].value
    h.eq(e.kind, "match")
    h.eq(#e.cases, 2)
    h.eq(e.cases[1].pattern.kind, "lit")
    h.eq(e.cases[1].pattern.value, 0)
    h.eq(e.cases[2].pattern.kind, "wildcard")
  end)
  h.it("parses a multi-statement block body", function()
    local p = prog("let f x = let y = x + 1 let z = y * 2 z")
    local body = p.stmts[1].value
    h.eq(body.kind, "block")
    h.eq(#body.stmts, 2)
    h.eq(body.result.kind, "ident")
    h.eq(body.result.name, "z")
  end)
end)
