local h = require("spec.support.harness")
local lexer = require("omelette.lexer")
local parser = require("omelette.parser")
local function cases(s) return assert(parser.parse("pub let f v = match v with " .. s)).stmts[1].value.cases end

h.describe("pattern parsing", function()
  h.it("lexes when as a keyword", function()
    local toks = assert(lexer.tokenize("x when y"))
    h.eq(toks[2], { type = "keyword", value = "when", line = 1, col = 3 })
  end)
  h.it("parses literal and wildcard (regression)", function()
    local c = cases("| 0 -> 1 | _ -> 2")
    h.eq(c[1].pattern, { kind = "lit", value = 0, lit_kind = "number" })
    h.eq(c[2].pattern.kind, "wildcard")
    h.eq(c[1].guard, nil)
  end)
  h.it("parses a variable pattern", function()
    local c = cases("| n -> n")
    h.eq(c[1].pattern, { kind = "var", name = "n" })
  end)
  h.it("parses an array pattern with nesting", function()
    local c = cases("| [a, [b, c]] -> a")
    h.eq(c[1].pattern.kind, "array_pat")
    h.eq(c[1].pattern.elems[1], { kind = "var", name = "a" })
    h.eq(c[1].pattern.elems[2].kind, "array_pat")
    h.eq(c[1].pattern.elems[2].elems[2], { kind = "var", name = "c" })
  end)
  h.it("parses a record pattern with pun and rename", function()
    local c = cases("| { x, y: b } -> x")
    h.eq(c[1].pattern.kind, "record_pat")
    h.eq(c[1].pattern.fields[1], { key = "x", pat = { kind = "var", name = "x" } })
    h.eq(c[1].pattern.fields[2].key, "y")
    h.eq(c[1].pattern.fields[2].pat, { kind = "var", name = "b" })
  end)
  h.it("parses a guard", function()
    local c = cases("| x when x > 0 -> 1 | _ -> 2")
    h.eq(c[1].pattern.kind, "var")
    h.eq(c[1].guard.kind, "binop")
    h.eq(c[1].guard.op, ">")
  end)
end)
