local h = require("spec.support.harness")
local parser = require("omelette.parser")
local function expr(s) return assert(parser.parse_expr_string(s)) end

h.describe("record update — parsing", function()
  h.it("parses `{ base with f = v }` as a record_update", function()
    local e = expr("{ c with radius = 5 }")
    h.eq(e.kind, "record_update")
    h.eq(e.base.kind, "ident")
    h.eq(e.base.name, "c")
    h.eq(#e.fields, 1)
    h.eq(e.fields[1].key, "radius")
    h.eq(e.fields[1].value.kind, "number")
    h.eq(e.fields[1].value.value, 5)
  end)
  h.it("parses multiple override fields", function()
    local e = expr("{ r with a = 1, b = 2 }")
    h.eq(e.kind, "record_update")
    h.eq(#e.fields, 2)
    h.eq(e.fields[2].key, "b")
  end)
  h.it("a non-ident base still parses (table literal base)", function()
    local e = expr("{ { a = 1 } with a = 2 }")
    h.eq(e.kind, "record_update")
    h.eq(e.base.kind, "table")
  end)
  h.it("a dict comprehension still parses (regression)", function()
    local e = expr("{ k => v | k, v <- m }")
    h.eq(e.kind, "dict_comprehension")
  end)
  h.it("a record literal still parses (regression)", function()
    local e = expr("{ x = 1 }")
    h.eq(e.kind, "table")
  end)
end)
