local h = require("spec.support.harness")
local repl = require("omelette.repl")

h.describe("repl", function()
  h.it("evaluates a bare expression to a value", function()
    local result, err = repl.eval_line("1 + 2", repl.new_session())
    h.truthy(err == nil)
    h.eq(result, 3)
  end)
  h.it("remembers let bindings across lines", function()
    local s = repl.new_session()
    local _, e1; _, e1, s = repl.eval_line("let x = 10", s)
    h.truthy(e1 == nil)
    local r2, e2 = repl.eval_line("x + 5", s)
    h.truthy(e2 == nil)
    h.eq(r2, 15)
  end)
  h.it("returns a diagnostic on a bad line without corrupting the session", function()
    local s = repl.new_session()
    local r, err = repl.eval_line('"oops', s)
    h.truthy(r == nil)
    h.truthy(err ~= nil)
    -- session still usable
    local r2 = repl.eval_line("1 + 1", s)
    h.eq(r2, 2)
  end)
end)
