local h = require("spec.support.harness")
local resolver = require("omelette.resolver")
local searcher = require("omelette.searcher")
local omelette = require("omelette")

h.describe("resolver", function()
  h.it("is an identity pass in v1", function()
    local prog = { kind = "program", stmts = {} }
    h.eq(resolver.resolve(prog), prog)
  end)
end)

h.describe("searcher", function()
  h.it("lets require load a .egg fixture", function()
    searcher.install({ "spec/fixtures/?.egg" })
    local mod = require("mathmod")
    h.eq(mod.square(4), 16)
    h.eq(mod.pi, 3.14)
  end)
end)

h.describe("public api", function()
  h.it("exposes compile/eval/install/version", function()
    h.truthy(type(omelette.compile) == "function")
    h.truthy(type(omelette.eval) == "function")
    h.truthy(type(omelette.install) == "function")
    h.truthy(type(omelette.version) == "string")
  end)
end)
