local h = require("spec.support.harness")
require("omelette.searcher").install()
local S = require("std.string")

h.describe("std.string", function()
  h.it("length/case", function()
    h.eq(S.length("hello"), 5)
    h.eq(S.upper("abc"), "ABC")
    h.eq(S.lower("ABC"), "abc")
  end)
  h.it("trim", function()
    h.eq(S.trim("  hi  "), "hi")
    h.eq(S.trim("nochange"), "nochange")
  end)
  h.it("starts_with/ends_with/contains", function()
    h.truthy(S.starts_with("hello", "he"))
    h.truthy(not S.starts_with("hello", "lo"))
    h.truthy(S.ends_with("hello", "lo"))
    h.truthy(S.contains("hello", "ell"))
    h.truthy(not S.contains("hello", "xyz"))
  end)
  h.it("split/join", function()
    h.eq(S.split("a,b,c", ","), {"a", "b", "c"})
    h.eq(S.split("nosep", ","), {"nosep"})
    h.eq(S.join({"a", "b", "c"}, "-"), "a-b-c")
  end)
  h.it("replace (literal)", function()
    h.eq(S.replace("a.b.c", ".", "-"), "a-b-c")
    h.eq(S.replace("aaa", "a", "bb"), "bbbbbb")
  end)
  h.it("rep", function()
    h.eq(S.rep("ab", 3), "ababab")
  end)
end)
