local h = require("spec.support.harness")
local lexer = require("omelette.lexer")
local parser = require("omelette.parser")
local function stmt(s) return assert(parser.parse(s)).stmts[1] end
local function expr(s) return assert(parser.parse_expr_string(s)) end
local function pat(s) return assert(parser.parse("pub let f v = match v with " .. s)).stmts[1].value.cases[1].pattern end

h.describe("sum type parsing", function()
  h.it("lexes type as a keyword", function()
    local toks = assert(lexer.tokenize("type X"))
    h.eq(toks[1], { type = "keyword", value = "type", line = 1, col = 1 })
  end)
  h.it("parses a type declaration with named-field + nullary variants", function()
    local d = stmt("type Shape = | Circle { radius } | Rect { width, height } | Origin")
    h.eq(d.kind, "type_decl"); h.eq(d.name, "Shape"); h.eq(d.is_pub, false)
    h.eq(d.variants[1], { name = "Circle", fields = { "radius" } })
    h.eq(d.variants[2], { name = "Rect", fields = { "width", "height" } })
    h.eq(d.variants[3], { name = "Origin", fields = {} })
  end)
  h.it("parses pub type", function()
    local d = stmt("pub type Option = | Some { value } | None")
    h.eq(d.kind, "type_decl"); h.eq(d.is_pub, true); h.eq(d.name, "Option")
  end)
  h.it("rejects a lowercase constructor", function()
    local _, err = parser.parse("type Bad = | circle { r }")
    h.truthy(err ~= nil)
    h.truthy(err.message:find("capitalized"))
  end)
  h.it("parses construction (fields and nullary)", function()
    local e = expr("Circle { radius = 5 }")
    h.eq(e.kind, "construct"); h.eq(e.tag, "Circle")
    h.eq(e.fields[1].key, "radius"); h.eq(e.fields[1].value.value, 5)
    h.eq(expr("None"), { kind = "construct", tag = "None", fields = {}, line = 1, col = 1 })
  end)
  h.it("still parses a lowercase ident as an ident (regression)", function()
    h.eq(expr("radius").kind, "ident")
  end)
  h.it("parses constructor patterns (fields, nullary, nested rename)", function()
    local p = pat("| Some { value } -> value")
    h.eq(p.kind, "ctor_pat"); h.eq(p.tag, "Some")
    h.eq(p.fields[1], { key = "value", pat = { kind = "var", name = "value" } })
    h.eq(pat("| None -> 0"), { kind = "ctor_pat", tag = "None", fields = {} })
    local n = pat("| Some { value: [a, b] } -> a")
    h.eq(n.fields[1].pat.kind, "array_pat")
  end)
end)
