local h = require("spec.support.harness")
require("omelette.searcher").install()
local T = require("std.table")

h.describe("std.table", function()
  h.it("keys/values (order-insensitive)", function()
    local ks = T.keys({ a = 1, b = 2 })
    local vs = T.values({ a = 1, b = 2 })
    table.sort(ks)
    table.sort(vs)
    h.eq(ks, { "a", "b" })
    h.eq(vs, { 1, 2 })
  end)
  h.it("get/has", function()
    h.eq(T.get({ x = 5 }, "x"), 5)
    h.truthy(T.has({ x = 5 }, "x"))
    h.truthy(not T.has({ x = 5 }, "y"))
  end)
  h.it("size", function()
    h.eq(T.size({ a = 1, b = 2, c = 3 }), 3)
    h.eq(T.size({}), 0)
  end)
end)
