local h = require("spec.support.harness")
local compiler = require("omelette.compiler")
local function eval(src) return assert(compiler.eval(src)) end

h.describe("tuples", function()
  h.it("builds and matches a 2-tuple", function()
    h.eq(eval("pub let r = match (1, 2) with | (a, b) -> a * 10 + b").r, 12)
  end)
  h.it("builds and matches a 3-tuple", function()
    h.eq(eval("pub let r = match (1, 2, 3) with | (a, b, c) -> a + b + c").r, 6)
  end)
  h.it("a tuple pattern can have a literal slot", function()
    h.eq(eval("pub let r = match (0, 5) with | (0, y) -> y | (x, y) -> x + y").r, 5)
    h.eq(eval("pub let r = match (3, 5) with | (0, y) -> y | (x, y) -> x + y").r, 8)
  end)
  h.it("grouping still returns the inner value (no comma)", function()
    h.eq(eval("pub let r = (1 + 2) * 3").r, 9)
  end)
  h.it("nests", function()
    h.eq(eval("pub let r = match ((1, 2), 3) with | ((a, b), c) -> a + b + c").r, 6)
  end)
  h.it("supports multiple-return via a tuple, matched out", function()
    h.eq(eval([[
let minmax a b = if a < b then (a, b) else (b, a)
pub let r = match minmax(5, 2) with | (lo, hi) -> hi - lo
]]).r, 3)
  end)
  h.it("a tuple expression parses to an `array` node", function()
    local e = assert(require("omelette.parser").parse_expr_string("(1, 2)"))
    h.eq(e.kind, "array")
    h.eq(#e.items, 2)
  end)
  h.it("the emitted Lua loads", function()
    local lua = assert(compiler.compile("pub let r = (1, 2, 3)"))
    local load_fn = loadstring or load
    h.truthy((load_fn(lua)))
  end)
end)
