local h = require("spec.support.harness")
local compiler = require("omelette.compiler")

h.describe("typecheck wiring", function()
  h.it("compile() without opts never checks (erase-and-run)", function()
    -- a type error, but no check requested -> compiles fine
    local lua, err = compiler.compile('let x: number = "hi"')
    h.truthy(err == nil)
    h.truthy(lua:find('x = "hi"', 1, true))
  end)
  h.it("compile(src, {check=true}) blocks on a type error", function()
    local lua, err = compiler.compile('let x: number = "hi"', { check = true })
    h.truthy(lua == nil)
    h.truthy(err ~= nil)
    h.truthy(err.message:find("number", 1, true))
  end)
  h.it("compile(src, {check=true}) passes a clean program through to Lua", function()
    local lua, err = compiler.compile("pub let add (x: number) (y: number): number = x + y", { check = true })
    h.truthy(err == nil)
    h.truthy(lua:find("function add"))
  end)
  h.it("check(src) returns all diagnostics", function()
    local d = assert(compiler.check('let x: number = "hi"'))
    h.truthy(#d >= 1)
    h.truthy(d[1].message:find("number", 1, true))
  end)
  h.it("check(src) on a clean program returns an empty list", function()
    h.eq(#assert(compiler.check("let count: number = 0")), 0)
  end)
  h.it("eval() still runs a type-erroneous program (runtime path never checks)", function()
    local mod = assert(compiler.eval('pub let x: number = "hi"'))
    h.eq(mod.x, "hi")
  end)
end)
