local h = require("spec.support.harness")
local parser = require("omelette.parser")
local tc = require("omelette.typecheck")
local compiler = require("omelette.compiler")
local function diags(s) return tc.check(assert(parser.parse(s))) end
local function ok(s) h.eq(#diags(s), 0) end
local function bad(s, needle)
  local d = diags(s)
  h.truthy(#d >= 1)
  h.truthy(d[1].message:find(needle, 1, true))
end
local SHAPE = "type Shape = | Circle { radius } | Rect { width, height } | Origin\n"
local OPT = "type Option = | Some { value } | None\n"

h.describe("typed sum types — exhaustiveness", function()
  h.it("a complete match is clean", function()
    ok(SHAPE .. "pub let f s = match s with | Circle { radius } -> radius | Rect { width } -> width | Origin -> 0")
  end)
  h.it("a missing constructor is flagged, naming the missing ones", function()
    local d = diags(SHAPE .. "pub let f s = match s with | Circle { radius } -> radius | Origin -> 0")
    h.truthy(#d >= 1)
    h.truthy(d[1].message:find("non-exhaustive", 1, true))
    h.truthy(d[1].message:find("Rect", 1, true))
  end)
  h.it("an unguarded wildcard catch-all makes it exhaustive", function()
    ok(SHAPE .. "pub let f s = match s with | Circle { radius } -> radius | _ -> 0")
  end)
  h.it("an unguarded variable catch-all makes it exhaustive", function()
    ok(SHAPE .. "pub let f s = match s with | Circle { radius } -> radius | other -> 0")
  end)
  h.it("a guarded constructor arm counts as covered", function()
    ok(OPT .. "pub let f o = match o with | Some { value } when value > 0 -> value | None -> 0")
  end)
  h.it("a guarded-only catch-all does NOT cover (still non-exhaustive)", function()
    bad(OPT .. "pub let f o n = match o with | Some { value } -> value | x when n > 0 -> 0", "None")
  end)
  h.it("mixed-type match is flagged", function()
    bad(SHAPE .. OPT .. "pub let f v = match v with | Circle { radius } -> radius | None -> 0", "mixes")
  end)
  h.it("a non-variant (literal) match is not exhaustiveness-checked", function()
    ok('pub let f n = match n with | 0 -> "z" | 1 -> "o"')
  end)
  h.it("undeclared constructors are lenient (no exhaustiveness)", function()
    ok("pub let f v = match v with | Some { value } -> value | None -> 0")
  end)
  h.it("a complete Option match is clean; a Some-only match is flagged", function()
    ok(OPT .. "pub let f o = match o with | Some { value } -> value | None -> 0")
    bad(OPT .. "pub let f o = match o with | Some { value } -> value", "None")
  end)

  h.it("wiring: non-exhaustive match blocks check/compile-with-check but still runs at runtime", function()
    local src = OPT .. "pub let f o = match o with | Some { value } -> value"
    -- omelette check / build path: blocks
    h.truthy(#assert(compiler.check(src)) >= 1)
    local lua, err = compiler.compile(src, { check = true })
    h.truthy(lua == nil and err ~= nil)
    -- runtime path: never checks → compiles and runs
    local mod = assert(compiler.eval(src))
    h.eq(mod.f({ __tag = "Some", value = 7 }), 7)
  end)
end)
