local h = require("spec.support.harness")
local parser = require("omelette.parser")
local tc = require("omelette.typecheck")
local function diags(s) return tc.check(assert(parser.parse(s))) end
local function ok(s) h.eq(#diags(s), 0) end
local function bad(s, needle)
  local d = diags(s)
  h.truthy(#d >= 1)
  h.truthy(d[1].message:find(needle, 1, true))
end
local SHAPE = "type Shape = | Circle { radius } | Rect { width, height } | Origin\n"

h.describe("typed sum types — construction & pattern validation", function()
  h.it("correct construction is clean", function()
    ok(SHAPE .. "pub let c = Circle { radius = 5 }")
    ok(SHAPE .. "pub let o = Origin")
  end)
  h.it("unknown field in construction is flagged", function()
    bad(SHAPE .. "pub let c = Circle { radiuz = 5 }", "radiuz")
  end)
  h.it("missing field in construction is flagged", function()
    bad(SHAPE .. "pub let c = Circle {}", "missing field 'radius'")
  end)
  h.it("extra field in construction is flagged", function()
    bad(SHAPE .. "pub let c = Circle { radius = 5, color = 1 }", "color")
  end)
  h.it("undeclared constructor is lenient (no diagnostic)", function()
    ok("pub let x = Whatever { anything = 1 }")
  end)
  h.it("construction field VALUES are still checked", function()
    bad(SHAPE .. 'pub let c = Circle { radius = 1 + "oops" }', "number")
  end)
  h.it("duplicate constructor across two types is flagged", function()
    bad("type A = | Dup { x }\ntype B = | Dup { y }", "Dup")
  end)
  h.it("unknown field in a constructor pattern is flagged (top-level and nested)", function()
    bad(SHAPE .. "pub let f s = match s with | Circle { bogus } -> bogus | _ -> 0", "bogus")
    bad("type W = | Wrap { inner }\n" ..
        "pub let f v = match v with | Wrap { inner: Circle { bogus } } -> 1 | _ -> 0"
        .. "\n" .. SHAPE, "bogus")
  end)
  h.it("partial (subset) destructuring in a pattern is clean", function()
    ok(SHAPE .. "pub let f s = match s with | Rect { width } -> width | _ -> 0")
  end)
end)
